name: Node.js CI

on:
  push:
    branches: [main, dev, add-tests]
  pull_request:
    branches: [main, dev, add-tests]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: get into backend project
        run: cd backend/
      - name: Create .env from .env.example
        run: cp .env.example .env
      - name: Install dependencies
        run: npm ci
      - name: Run the tests
        run: npm run test
